{
  description = "make2flake flake (generated by make2flake lol)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in {
        packages = {
          default = pkgs.stdenv.mkDerivation {
            pname = "make2flake";
            version = "0.1.0";
            src = ./.;

            nativeBuildInputs = with pkgs; [
            ];

            buildInputs = with pkgs; [
              # No build dependencies detected
            ];

            buildPhase = ''
              make -j$NIX_BUILD_CORES
            '';

            installPhase = ''
              make install DESTDIR=$out PREFIX=$out
            '';

            makeFlags = [
              "PREFIX=$(out)"
              "DESTDIR="
            ];
          };
        };

        devShells = {
          default = pkgs.mkShell {
            buildInputs = with pkgs; [
              # No dependencies detected
              # Add development tools here
            ];
            shellHook = ''
            '';
          };
        };
      }
    );
}
